apiVersion: v1
kind: Pod
metadata:
  name: triton-ubuntu-test
spec:
  containers:
  - image: 7b5981c4-1889-11e7-b4c5-3f3bdfc9b88b
    name: triton-ubuntu-test
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
