apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
    matchExpressions:
      - {key: app, operator: In, values: [ubuntu]}
  template:
    metadata:
      annotations:
        package: b87c2a29-6b6a-6d19-ea65-aa81e680002c # Put the package you want
        networks: 17d7aa50-6ad9-4e56-93b7-12dc868fac2a # Put the networks your want
        fwgroup: ubuntu  
        fwenabled: "true"
      labels:
        app: ubuntu
        triton.cns.services: ubuntu
    spec:
      restartPolicy: Always
      containers:
      - image: 7b5981c4-1889-11e7-b4c5-3f3bdfc9b88b
        name: consul
        ports:
          - containerPort: 22
            name: ssh
        env:
          - name: foo
            value: "bar"
          - name: bar
            value: "baz"
        readinessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 10
          periodSeconds: 5
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
